# Numpy

Numpy es un paquete de computación científica. Permite el trabajo con arreglos vectoriales, matriciales y funciones para cálculos matemáticos. Para mayor información ir a: __[Numpy](https://docs.scipy.org/doc/numpy/user/quickstart.html)__

En este notebook se abordarán temas como:

[1. Crear arreglos (arrays) utilizando NumPy](#seccion 1)

[2. Información de los arreglos](#seccion 2)

[3. Acceder y modificar elementos en un arreglo](#seccion 3)

[4. Acceder a sub arreglos](#seccion 4)

[5. Partición de datos](#seccion 5)

[6. Operaciones con arreglos](#seccion 6)

[7. Operaciones booleanas](#seccion 7)

[8. Ordenar arreglos](#seccion 8)

In [2]:
import numpy as np

###   <a id='seccion 1'></a>1. Crear arreglos (arrays) utilizando NumPy

In [3]:
np?

Los arrays son arreglos de datos en diferentes dimensiones, similares a las listas pero más eficiente, por lo que la manipulación de datos en python es sinónimo de manipulación en Numpy, incluso en el uso de otras herramientas como Pandas

Estos arreglos deben tener el mismo tipo de dato para realizar las operaciones entre ellos y para su creación

In [4]:
# Crear un vector o array de 1 dimensión

a=np.array([12,32,34,32,22,15])

# Crear una matriz o array de 2 dimensiones

b=np.array([[12,13,54],[12,32,1],[21,3,4]])
print( a,"\n\n", b)

[12 32 34 32 22 15] 

 [[12 13 54]
 [12 32  1]
 [21  3  4]]


In [43]:
# Qué sucede si se crea un array con diferentes tipos de variables

c=np.array(["1",2,3,4.5])
print(c) # Numpy modifica el tipo de la variable para que todas sean iguales (respecto al tipo)

['1' '2' '3' '4.5']


Para crear algunos arreglos específicos NumPy cuenta con funciones pre definidas

In [47]:
# Crear un array de 0
print(np.zeros(10,dtype="int"))

[0 0 0 0 0 0 0 0 0 0]


In [48]:
# Crear una matriz de 1

print(np.ones((3,4),dtype="float"))


 [[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [50]:
# Crear una matriz con un valor cualquiera (i.e 14.8)

print(np.full((2,3),14.8,dtype="float"))

[[ 14.8  14.8  14.8]
 [ 14.8  14.8  14.8]]


In [51]:
# Crear un arreglo entre dos valores (0,20) tomando cierto tamaño de "paso" (2)

print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [52]:
# Crear una matriz identidad

print(np.eye(4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [53]:
# Crear una matriz de valores aleatorios

print(np.random.rand(5,5)) # Número de filas y número de columnas

[[ 0.77905102  0.8649333   0.41139672  0.13997259  0.03322239]
 [ 0.98257496  0.37329075  0.42007537  0.05058812  0.36549611]
 [ 0.01662797  0.23074234  0.7649117   0.94412352  0.74999925]
 [ 0.33940382  0.48954894  0.33898512  0.17949026  0.1709866 ]
 [ 0.46345098  0.87457296  0.94411975  0.60825287  0.59665541]]


### <a id='seccion 2'></a>2. Información de los arreglos

In [75]:
np.random.seed(0) # Asignar y mantener fija la semilla en el generador de valores aleatorios

x=np.random.randint(10,size=(3,4))
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


Para conocer las características de los arreglos como dimensiones, forma y tamaño se utilizan los siguientes métodos:

In [76]:
# Dimensiones (ndim)

print(x.ndim)

2


In [58]:
# Forma

print(x.shape)

(3, 4)


In [57]:
# Tamaño

print(x.size)

12


### <a id='seccion 3'></a>3. Acceder y modificar elementos en los arreglos 

El acceso y modificación de un elemento en un array se hace de manera similar a las listas, es decir, usando [fila,columna]

In [77]:
print(x) 

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [71]:
# Acceder al primer elemento

print("Primer elemento: ",x[0])

Primer elemento:  [5 0 3 3]


In [63]:
# Acceder al último elemento

print("Último elemeno: ",x[-1])

Último elemeno:  [2 4 7 6]


In [70]:
# Acceder a cualquier elemento (i.e tercer elemento de la primera fila)

print(x[0,3])

3


In [72]:
# Modificar un elemento 

x[1]=3.16 # Modificar todos los elementos de la fila 1
print(x)

[[5 0 3 3]
 [3 3 3 3]
 [2 4 7 6]]


### <a id='seccion 4'></a>4. Acceder a sub-arreglos

Al igual que en las listas, para acceder a porciones o sub-arreglos se usa la notación:

x[comienzo:final:paso]

In [79]:
# Arreglo unidimensional

x1=[12,7,34,5,6,78]
print(x1)
print(x1[:2])

[12, 7, 34, 5, 6, 78]
[12, 7]


In [80]:
# Dos últimos elementos

print(x1[-2:])

[6, 78]


In [81]:
# Elementos cada dos observaciones

print(x1[::2] )

[12, 34, 6]


In [85]:
# Arreglo multidimensional

print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [87]:
# Primera columna

print(x[:,0])

[5 7 2]


In [88]:
# Primeras dos filas y tres columnas

print(x[:2,:3])

[[5 0 3]
 [7 9 3]]


In [91]:
# Todas las filas y columnas intercaladas
print(x[:,::2])

[[5 3]
 [7 3]
 [2 7]]


### <a id='seccion 5'></a>5. Particionar los datos

En algunos casos es preciso modificar la forma de un array, por lo que la función reshape resulta util para esta tarea

In [120]:
grid=np.arange(16) # Se crea un array unidimensional con 16 elementos
grid= grid.reshape((4,4)) # Se modifica a una matriz de 4x4
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [121]:
# Partición vertical en dos de un arreglo (de forma equitativa)
upper, lower=np.vsplit(grid,2) 
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [122]:
# Partición horizontal en dos de un arreglo (de forma equitativa)

left,right=np.hsplit(grid,[2])
print("\n",left)
print(right)


 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### <a id='seccion 6'></a>6. Operaciones con los arreglos

* Funciones aritméticas

En la siguiente tabla se enlistan los operadores aritméticos implementados en NumPy:

| Operador	    | Equivalente ufunc | Descripción                           |
|---------------|-------------------|---------------------------------------|
|``+``          |``np.add``         |Suma (e.g., ``1 + 1 = 2``)             |
|``-``          |``np.subtract``    |Resta (e.g., ``3 - 2 = 1``)            |
|``-``          |``np.negative``    |Negativo unitario (e.g., ``-2``)       |
|``*``          |``np.multiply``    |Multiplicación (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``      |División (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``|División inferior (e.g., ``3 // 2 = 1``)|
|``**``         |``np.power``       |Potenciación (e.g., ``2 ** 3 = 8``)    |
|``%``          |``np.mod``         |Módulo/residuo (e.g., ``9 % 4 = 1``)   |


In [126]:
print(np.floor_divide(grid,3)) # Aproximación al entero inferior

[[0 0 0 1]
 [1 1 2 2]
 [2 3 3 3]
 [4 4 4 5]]


* Funciones trigonométricas

In [127]:
theta=np.linspace(0,np.pi,3)
print(theta)
print("\n Seno(theta):",np.sin(theta))
print("\n Coseno(theta):",np.cos(theta))
print("\n Tangente(theta):",np.tan(theta))

[ 0.          1.57079633  3.14159265]

 Seno(theta): [  0.00000000e+00   1.00000000e+00   1.22464680e-16]

 Coseno(theta): [  1.00000000e+00   6.12323400e-17  -1.00000000e+00]

 Tangente(theta): [  0.00000000e+00   1.63312394e+16  -1.22464680e-16]


* Funciones logarítmicas y exponenciales

In [128]:
# Funciones exponenciales
x = [1, 2, 3]
print("x:   ", x)
print("x^3: ", np.power(x,3))
print("e^x: ", np.exp(x))
print("2^x: ", np.exp2(x))
print("3^x: ", np.power(3, x))

x:    [1, 2, 3]
x^3:  [ 1  8 27]
e^x:  [  2.71828183   7.3890561   20.08553692]
2^x:  [ 2.  4.  8.]
3^x:  [ 3  9 27]


In [129]:
# Funciones logarítmicas
x = [1, 2, 4, 10]
print("x        :", x)
print("ln(x)    :", np.log(x))
print("log2(x)  :", np.log2(x))
print("log10(x) :", np.log10(x))

x        : [1, 2, 4, 10]
ln(x)    : [ 0.          0.69314718  1.38629436  2.30258509]
log2(x)  : [ 0.          1.          2.          3.32192809]
log10(x) : [ 0.          0.30103     0.60205999  1.        ]


* Otras funciones

In [131]:
print(x)
print(np.multiply.reduce(x))     # Reducir el arreglo a una sola operación. Regresa el producto de todos los elementos
print(np.multiply.accumulate(x)) # Multiplica todos los elementos y almacena los productos intermedios

[1, 2, 4, 10]
80
[ 1  2  8 80]


Para la multiplicación de matrices se usa la función np.dot(), en el caso de querer multiplicar elemento por elemento se acude a " * "

In [137]:
# Para el producto de las matrices se debe cumplir que las dimensiones sean: (mxn)*(nxp)=mxp

a=np.random.rand(4,5) # Matriz de 4x5
b=np.random.randint(0,5,size=[5,3]) # Matríz de 5x3
n=a.dot(b)
print(n)

[[  4.20465696   3.75876854   6.18519781]
 [  7.18547793   4.27075002   9.06916324]
 [  9.13237162   6.54584967  12.64810648]
 [  6.71123      3.18346481   7.94624615]]


In [138]:
# La función transpose regresa la transupuesta de una matriz

trans=a.transpose()
print("Transpuesta de la matriz: \n\n",trans)

Transpuesta de la matriz: 

 [[ 0.09088573  0.61882617  0.92234798  0.91978281]
 [ 0.2277595   0.13346147  0.54138079  0.03603382]
 [ 0.41030156  0.98058013  0.92330607  0.174772  ]
 [ 0.62329467  0.87178573  0.82989737  0.38913468]
 [ 0.88696078  0.50272076  0.96828641  0.9521427 ]]


In [140]:
# Inversa de una matriz. Es preciso acudir al modulo de álgebra lineal (linalg)

matriz=np.random.randint(4,100,[4,4])
inv=np.linalg.inv(matriz)
print(matriz,"\n")
print(inv,"\n")
print(matriz.dot(inv))

[[34 23  8 24]
 [78 71 90 64]
 [97 45 44 64]
 [85 55 44 63]] 

[[  2.03146951e-01   4.07551613e-02   9.49571174e-02  -2.15255757e-01]
 [  2.00899129e-01   3.88552162e-02  -8.02793722e-05  -1.15923413e-01]
 [ -2.96431582e-02   1.66111401e-02   1.75276629e-02  -2.33880571e-02]
 [ -4.28772127e-01  -1.00509774e-01  -1.40288203e-01   4.23834946e-01]] 

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   8.88178420e-16]
 [ -1.77635684e-15   1.00000000e+00  -1.77635684e-15   3.55271368e-15]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [141]:
# Determinante de una matriz

np.linalg.det(matriz)

149477.9999999998

In [142]:
# La función flatten transforma un arreglo n-dimensional en uno uni dimensional

uni=a.flatten()
print(uni,"\n",uni.shape)

[ 0.09088573  0.2277595   0.41030156  0.62329467  0.88696078  0.61882617
  0.13346147  0.98058013  0.87178573  0.50272076  0.92234798  0.54138079
  0.92330607  0.82989737  0.96828641  0.91978281  0.03603382  0.174772
  0.38913468  0.9521427 ] 
 (20,)


### <a id='seccion 7'></a>7. Operaciones booleanas

In [143]:
x=np.random.randint(low=0,high=10,size=(4,2))
x

array([[1, 5],
       [8, 0],
       [3, 7],
       [1, 7]])

In [144]:
# Para comparar elementos de un arreglo se hace uso de los operadores booleanos

print(x>4) # Como salida se obtiene el arreglo del mismo tamaño, pero con valores de true cuando se cumple la condición

[[False  True]
 [ True False]
 [False  True]
 [False  True]]


In [145]:
# Los valores de True son iguales a 1, para contar cuantos valores cumplen con una condición se hace uso de count_nonzero()

print(np.count_nonzero(x>5),"valores son mayores a 5")
print(np.count_nonzero(~(x>=5)),"valores no son mayores a 5")
print(np.count_nonzero((x>5)&(x<8)),"valores son mayores a 5 y menores a 8")
print(np.count_nonzero((x>5)|(x<8)),"valores son mayores a 5 o menores a 8")

3 valores son mayores a 5
4 valores no son mayores a 5
2 valores son mayores a 5 y menores a 8
8 valores son mayores a 5 o menores a 8


In [146]:
# Para seleccionar un subconjuto de datos que cumpla una condición se crea una "máscara"

mask=x>6
print("Los valores mayores 6 son:",x[mask])

Los valores mayores 6 son: [8 7 7]


Los operadores and y or no son equivalentes a & y |, dado que los primeros toman una única entidad para realizar las comparaciones, mientras que los segundos lo hacen elemento por elemento

### <a id='seccion 8'></a>8. Ordenar los arreglos

Para ordenar los arreglos en NumPy se pueden usar bucles, sin embargo resulta más eficiente utilizar las funciones con las que se cuenta como sort() o argsort

In [147]:
x=np.random.randint(0,20,10)
x

array([ 8,  0,  5, 15,  6, 15,  5,  9, 17, 16])

In [33]:
# Ordenar los valores de menor a mayor
print(np.sort(x))

# Ordenar de menor a mayor, pero regresando los índicies de los valores ordenados
print(np.argsort(x))

[ 4  6  7  8  9 11 13 15 15 18]
[0 1 3 7 5 9 2 4 8 6]


In [34]:
z=np.random.randint(0,10,(4,6))
z

array([[6, 9, 1, 6, 8, 8],
       [3, 2, 3, 6, 3, 6],
       [5, 7, 0, 8, 4, 6],
       [5, 8, 2, 3, 9, 7]])

In [35]:
# Ordenar las columnas
print(np.sort(z,axis=0))

# Ordenar las filas
print("\n",np.sort(z,axis=1))

[[3 2 0 3 3 6]
 [5 7 1 6 4 6]
 [5 8 2 6 8 7]
 [6 9 3 8 9 8]]

 [[1 6 6 8 8 9]
 [2 3 3 3 6 6]
 [0 4 5 6 7 8]
 [2 3 5 7 8 9]]


In [153]:
np.random.randint(low=0,high=50,size=20)

array([46,  5, 19, 47, 22, 45, 11, 11, 33,  7, 26, 48,  7, 47, 32, 36, 18,
       23, 21,  2])

### Ejercicio


1) Cree un arreglo unidimensional con los siguientes valores:

    46, 5, 19, 47, 22, 45, 11, 11, 33, 7, 26, 48, 7, 47, 32, 36, 18, 23, 21, 2
    
    - ¿Cuál es su tamaño, dimensión y forma?

2) Convierta el arreglo anterior en una matriz de 6x3, ¿Es posible?, de no ser así proponga una forma que sí lo permita.

3) ¿Cuál es el valor de la posición (2,3)? Cambie su valor por 8

4) De la matriz extraiga la primera y última fila y cree dos variables nuevas. ¿Cuál es el valor de su suma?

5) Cree una matriz de enteros de tamaño 20 y ordene sus valores 